### PR TITLE
Bring SWAPPINESS governor to master and add a config to enable it.

### PR DESCRIPTION
**Pull request by Rp70**
I currently use your script and found it's helpful with SWAPPINESS governor. But the branch 'Swapiness-load-balancer' is a bit out-of-date, so I bring the governor the to master branch and add a config option to enable. I hope this is useful to everyone. Thanks for the great script!

### CODE REVIEW

**Comment by StuartIanNaylor** [comment]
I think the swapiness load governor went on a backburner and stayed there as its started to get less relevent with the Pi3 and the oompf of the Pi sales with very high swapiness no problem.

I meant to get a bit more creative rather than just load but the actually zram stats.
Have you got and ideas?
Or do you think its prob not needed?

**Comment by Rp70** [comment]
I don't use Pi. I use your script on Ubuntu on dedicated servers. In my environment, that's okay with swapniness and a higer load.

**Comment by StuartIanNaylor** [comment]
> I don't use Pi. I use your script on Ubuntu on dedicated servers. In my environment, that's okay with swapniness and a higer load.

Yeah zram is memory but the simple parameter change to PAGE_CLUSTER to zero and instant writes helps much with latency.
I don't think many setups really have HardDrive swap for performance anymore but they default if not changed queues in batches of 8 which might of been good for HardDrive isn't good for SSD though and definately not memory based zram.
I presum if you are running server sevices that are mem intensive or a lot of instances it likely helps much.

Shouldn't be using this script though as Ubuntu and the main distro's need to update there zram scripts so they catch up with zram and much change in technology.
I keep meaning to perf test the LZO-RLE alg its not mentioned but you can use any kernel compression alg.

Its only the zero/pi2 level that can incur load at boot. 

Think its best to keep branches seperate create a pull request against swapiness-load-balancer branch rather than master, but really you can just set high as default

**Comment by Rp70** [comment]
Sorry for the delay in response. I understand your points now. Thank you for the suggestion.

**Pull request closed without merging**
